name: Testing this apps
run-name: ${{ github.actor }} Testing this apps 
on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
      - run: npm install dependencies
      - name: Launch the apps
      - run: npm start
